### ISSUE TITLE
Raw Time import should match bibs with extra zeros

### ISSUE THREAD

**Issue by moveson** [SplitTime/OpenSplitTime#233]
Currently, if a user imports raw times having a bib number with an extra zero in front, like `020`, the importer does not match this to bib `20`.

**Comment by moveson** [comment]
Also, the unmatched time results in a 500 error in the sidekiq worker:
```

458 <190>1 2020-02-13T09:53:53.418584+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a]   [1m[36mSplitTime Exists (1.1ms)[0m  [1m[34mSELECT  1 AS one FROM "split_times" WHERE "split_times"."split_id" IS NULL AND "split_times"."effort_id" = $1 AND "split_times"."sub_split_bitkey" = $2 AND "split_times"."lap" = $3 LIMIT $4[0m  [["effort_id", 4290], ["sub_split_bitkey", 1], ["lap", 1], ["LIMIT", 1]]Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29302/13/202002:53:53.420 -0700187 <190>1 2020-02-13T09:53:53.420434+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a]   [1m[35m (0.8ms)[0m  [1m[31mROLLBACK[0mHost: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29402/13/202002:53:53.423 -0700339 <190>1 2020-02-13T09:53:53.423145+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a] Error performing ProcessImportedRawTimesJob (Job ID: b05beec2-d53b-41d0-8450-1e8daf588c0a) from Sidekiq(default) in 406.23ms: NoMethodError (undefined method `distance_from_start' for nil:NilClass):Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29502/13/202002:53:53.423 -0700125 <190>1 2020-02-13T09:53:53.423146+00:00 host app worker.1 - /app/app/models/split_time.rb:94:in `distance_from_start_of_lap'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29602/13/202002:53:53.423 -0700124 <190>1 2020-02-13T09:53:53.423147+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `block in ordered_split_times'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29702/13/202002:53:53.423 -0700170 <190>1 2020-02-13T09:53:53.423148+00:00 host app worker.1 - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29802/13/202002:53:53.423 -0700170 <190>1 2020-02-13T09:53:53.423148+00:00 host app worker.1 - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 29902/13/202002:53:53.423 -0700103 <190>1 2020-02-13T09:53:53.423149+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `sort_by'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku 30002/13/202002:53:53.423 -0700115 <190>1 2020-02-13T09:53:53.423149+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `ordered_split_times' | 458 <190>1 2020-02-13T09:53:53.418584+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a]   [1m[36mSplitTime Exists (1.1ms)[0m  [1m[34mSELECT  1 AS one FROM "split_times" WHERE "split_times"."split_id" IS NULL AND "split_times"."effort_id" = $1 AND "split_times"."sub_split_bitkey" = $2 AND "split_times"."lap" = $3 LIMIT $4[0m  [["effort_id", 4290], ["sub_split_bitkey", 1], ["lap", 1], ["LIMIT", 1]]Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 293 | 02/13/202002:53:53.420 -0700 | 187 <190>1 2020-02-13T09:53:53.420434+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a]   [1m[35m (0.8ms)[0m  [1m[31mROLLBACK[0mHost: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 294 | 02/13/202002:53:53.423 -0700 | 339 <190>1 2020-02-13T09:53:53.423145+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a] Error performing ProcessImportedRawTimesJob (Job ID: b05beec2-d53b-41d0-8450-1e8daf588c0a) from Sidekiq(default) in 406.23ms: NoMethodError (undefined method `distance_from_start' for nil:NilClass):Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 295 | 02/13/202002:53:53.423 -0700 | 125 <190>1 2020-02-13T09:53:53.423146+00:00 host app worker.1 - /app/app/models/split_time.rb:94:in `distance_from_start_of_lap'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 296 | 02/13/202002:53:53.423 -0700 | 124 <190>1 2020-02-13T09:53:53.423147+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `block in ordered_split_times'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 297 | 02/13/202002:53:53.423 -0700 | 170 <190>1 2020-02-13T09:53:53.423148+00:00 host app worker.1 - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 298 | 02/13/202002:53:53.423 -0700 | 170 <190>1 2020-02-13T09:53:53.423148+00:00 host app worker.1 - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 299 | 02/13/202002:53:53.423 -0700 | 103 <190>1 2020-02-13T09:53:53.423149+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `sort_by'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku | 300 | 02/13/202002:53:53.423 -0700 | 115 <190>1 2020-02-13T09:53:53.423149+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `ordered_split_times'
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
458 <190>1 2020-02-13T09:53:53.418584+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a]   [1m[36mSplitTime Exists (1.1ms)[0m  [1m[34mSELECT  1 AS one FROM "split_times" WHERE "split_times"."split_id" IS NULL AND "split_times"."effort_id" = $1 AND "split_times"."sub_split_bitkey" = $2 AND "split_times"."lap" = $3 LIMIT $4[0m  [["effort_id", 4290], ["sub_split_bitkey", 1], ["lap", 1], ["LIMIT", 1]]Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
293 | 02/13/202002:53:53.420 -0700 | 187 <190>1 2020-02-13T09:53:53.420434+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a]   [1m[35m (0.8ms)[0m  [1m[31mROLLBACK[0mHost: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
294 | 02/13/202002:53:53.423 -0700 | 339 <190>1 2020-02-13T09:53:53.423145+00:00 host app worker.1 - [ActiveJob] [ProcessImportedRawTimesJob] [b05beec2-d53b-41d0-8450-1e8daf588c0a] Error performing ProcessImportedRawTimesJob (Job ID: b05beec2-d53b-41d0-8450-1e8daf588c0a) from Sidekiq(default) in 406.23ms: NoMethodError (undefined method `distance_from_start' for nil:NilClass):Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
295 | 02/13/202002:53:53.423 -0700 | 125 <190>1 2020-02-13T09:53:53.423146+00:00 host app worker.1 - /app/app/models/split_time.rb:94:in `distance_from_start_of_lap'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
296 | 02/13/202002:53:53.423 -0700 | 124 <190>1 2020-02-13T09:53:53.423147+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `block in ordered_split_times'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
297 | 02/13/202002:53:53.423 -0700 | 170 <190>1 2020-02-13T09:53:53.423148+00:00 host app worker.1 - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
298 | 02/13/202002:53:53.423 -0700 | 170 <190>1 2020-02-13T09:53:53.423148+00:00 host app worker.1 - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
299 | 02/13/202002:53:53.423 -0700 | 103 <190>1 2020-02-13T09:53:53.423149+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `sort_by'Host: host  Name: d.bc84453f-1b5f-43e1-94bf-a4f313a09d59  Category: heroku
300 | 02/13/202002:53:53.423 -0700 | 115 <190>1 2020-02-13T09:53:53.423149+00:00 host app worker.1 - /app/app/models/effort.rb:238:in `ordered_split_times'


```
