### ISSUE TITLE
Fix spec that fails occasionally

### ISSUE THREAD

**Issue by moveson** [SplitTime/OpenSplitTime#506]
We are seeing a spec that fails from time to time, maybe 1 in 20 runs:

https://dashboard.heroku.com/pipelines/61527d5c-7d41-4b41-821c-c64a2d79dfeb/tests/1939

```
Failures:
  1) Interactors::UpdateEventAndGrouping.perform! when the event is changing to a new event_group and the old event_group has any remaining events creates a new event and assigns it to the subject event but does not destroy the old event_group
     Failure/Error: let!(:other_event) { create(:event, :with_short_name, event_group: old_event_group) }
     ActiveRecord::RecordInvalid:
       Validation failed: Short name has already been taken
     # ./spec/services/interactors/update_event_and_grouping_spec.rb:30:in `block (4 levels) in <top (required)>'
```

**Comment by moveson** [comment]
Here's another one that fails occasionally:

```
  1) Interactors::ChangeEventCourse#perform! when the new course has splits with the same distances as the old makes no changes and returns an unsuccessful response with errors if names do not coincide
     Failure/Error: let(:new_split_1) { create(:split, :start, base_name: "Start") }
     ActiveRecord::RecordInvalid:
       Validation failed: Name has already been taken
     # <internal:kernel>:90:in `tap'
     # <internal:kernel>:90:in `tap'
     # <internal:kernel>:90:in `tap'
     # ./spec/services/interactors/change_event_course_spec.rb:44:in `block (4 levels) in <top (required)>'
     # ./spec/services/interactors/change_event_course_spec.rb:48:in `block (4 levels) in <top (required)>'
     # ./spec/services/interactors/change_event_course_spec.rb:43:in `block (4 levels) in <top (required)>'
     # ./spec/services/interactors/change_event_course_spec.rb:53:in `block (4 levels) in <top (required)>'
```
